CREATE TABLE [dbo].[Contracts] (
    [Id]                      INT           IDENTITY (1, 1) NOT NULL,
    [OrganizationId]           INT           NULL,
    [ContractNumber]             VARCHAR (100) NULL,
    [Name]                   VARCHAR (100) NULL,
    [ContractTypeId]                   INT           NULL,
    [ContractStateId]                  INT           NULL,
    [EffortsCount]            INT           NULL,
    [EffortsPeriod]          INT           NULL,
    [EffortsPeriodMeasurementUnitId]  INT           NULL,
    [ContractEffectiveDate]        DATETIME      NULL,
    [ContractLegalDate]   DATETIME      NULL,
    [FixedContractExpirationDate]            BIT           NULL,
    [ContractExpirationDate]      DATETIME      NULL,
    [ResponsibleEmployeeId]              INT           NULL,
    [AsignmentDate]         DATETIME      NULL,
    [AgreedPrice]           MONEY         NULL,
    [InvoicePeriod]           INT           NULL,
    [InvoicePeriodMeasurementUnitId] INT           NULL,
    [UpdateEmployeeId]               INT           NULL,
    [DateUpdated]          DATETIME      NULL,
    CONSTRAINT [PK_Contracts] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Contracts_Organizations] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organizations] ([Id]),
    CONSTRAINT [FK_Contracts_InvoicePeriodMeasurementUnits] FOREIGN KEY ([InvoicePeriodMeasurementUnitId]) REFERENCES [dbo].[MeasurementUnits] ([Id]),
    CONSTRAINT [FK_Contracts_EffortsPeriodMeasurementUnits] FOREIGN KEY ([EffortsPeriodMeasurementUnitId]) REFERENCES [dbo].[MeasurementUnits] ([Id]),
    CONSTRAINT [FK_Contracts_UpdateEmployees] FOREIGN KEY ([UpdateEmployeeId]) REFERENCES [dbo].[Employees] ([Id]),
    CONSTRAINT [FK_Contracts_ResponsibleEmployees] FOREIGN KEY ([ResponsibleEmployeeId]) REFERENCES [dbo].[Employees] ([Id]),
    CONSTRAINT [FK_Contracts_ContractStates] FOREIGN KEY ([ContractStateId]) REFERENCES [dbo].[ContractStates] ([Id]),
    CONSTRAINT [FK_Contracts_ContractTypes] FOREIGN KEY ([ContractTypeId]) REFERENCES [dbo].[ContractTypes] ([Id])
);

