CREATE TABLE [dbo].[Courses] (
	[Id]                        INT           IDENTITY (1, 1) NOT NULL,
	[Reference]                VARCHAR (50)  NULL,
	[Name]                     VARCHAR (200) NULL,
	[CourseTypeId]                     INT           NULL,
	[CourseDate]               DATETIME      NULL,
	[NextCourseDate]               DATETIME      NULL,
	[LectorId]                INT           NULL,
	[OrganizationId]             INT           NULL,
	[CourseKindId]                    INT           NULL,
	[CourseAttendeeTypeId]                 INT           NULL,
	[CoursePlace]             VARCHAR (200) NULL,
	[AttendeeCount]               INT           NULL,
	[PassedCount]                  INT           NULL,
	[FailedCount]                INT           NULL,
	[CommitteeHeadId]         INT           NULL,
	[CommitteeMember1Id]            INT           NULL,
	[CommitteeMember2Id]            INT           NULL,
	[CourseExamTypeId]           INT           NULL,
	[ContractId]                  INT           NULL,
	[NotificatedId]            INT           NULL,

	[LicenseReleaseDate]            DATETIME      NULL,
	[LicenseReleasedBy]             VARCHAR (100) NULL,

	/*These should be custom attributes*/
	[Vyska15]                   BIT           NULL,
	[Plosina]                   BIT           NULL,
	[Rebrik5]                   BIT           NULL,
	[Hlbka13]                   BIT           NULL,
	[Postroj]                   VARCHAR (100) NULL,

	[CisloPreukazu]             VARCHAR (20)  NULL,
	[I]                         BIT           NULL,
	[A]                         BIT           NULL,
	[B]                         BIT           NULL,
	[C]                         BIT           NULL,
	[D]                         BIT           NULL,
	[E]                         BIT           NULL,
	[W1]                        BIT           NULL,
	[W2]                        BIT           NULL,
	[G]                         BIT           NULL,
	[II]                        BIT           NULL,
	[Z]                         BIT           NULL,
	[C_BezVodickehoOpravnenia]  BIT           NULL,
	[W1_BezVodickehoOpravnenia] BIT           NULL,
	[Z_PocetHodin]              FLOAT (53)    NULL,
	CONSTRAINT [PK_Courses] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Course_CommitteeMember1] FOREIGN KEY ([CommitteeMember1Id]) REFERENCES [dbo].[Employees] ([Id]),
	CONSTRAINT [FK_Course_CommitteeMember2] FOREIGN KEY ([CommitteeMember2Id]) REFERENCES [dbo].[Employees] ([Id]),
	CONSTRAINT [FK_Course_Notificated] FOREIGN KEY ([NotificatedId]) REFERENCES [dbo].[Employees] ([Id]),
	CONSTRAINT [FK_Course_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organizations] ([Id]),
	CONSTRAINT [FK_Course_CommitteeHead] FOREIGN KEY ([CommitteeHeadId]) REFERENCES [dbo].[Employees] ([Id]),
	CONSTRAINT [FK_Course_CourseKind] FOREIGN KEY ([CourseKindId]) REFERENCES [dbo].[CourseKinds] ([Id]),
	CONSTRAINT [FK_Course_CourseExamType] FOREIGN KEY ([CourseExamTypeId]) REFERENCES [dbo].[CourseExamTypes] ([Id]),
	CONSTRAINT [FK_Course_CoureAttendeeType] FOREIGN KEY ([CourseAttendeeTypeId]) REFERENCES [dbo].[CourseAttendeeTypes] ([Id]),
	CONSTRAINT [FK_Course_CourseType] FOREIGN KEY ([CourseTypeId]) REFERENCES [dbo].[CourseTypes] ([Id]),
	CONSTRAINT [FK_Course_Lector] FOREIGN KEY ([LectorId]) REFERENCES [dbo].[Employees] ([Id]),
	CONSTRAINT [FK_Course_Contract] FOREIGN KEY ([ContractId]) REFERENCES [dbo].[Contracts] ([Id])
);

