CREATE TABLE [dbo].[Tasks] (
    [Id]                  INT           IDENTITY (1, 1) NOT NULL,
    [ContractId]            INT           NULL,
    [TaskTypeId]               INT           NULL,
    [TaskStateId]              INT           NULL,
    [Order]             INT           NULL,
    [PortfolioId]         INT           NULL,
    [PortfolioPeriod]    INT           NULL,
    [PortfolioMeasurementUnitId] INT           NULL,
    [StartupWorkId]       INT           NULL,
    [Name]               VARCHAR (50)  NULL,
    [Description]               VARCHAR (MAX) NULL,
    [Deadline]            DATETIME      NULL,
    [PlannedDate]                DATETIME      NULL,
    [SolverEmployeeId]            INT           NULL,
    [OutsourcedSolver]         VARCHAR (100) NULL,
    [DateSolved]        DATETIME      NULL,
    [Note]              VARCHAR (MAX) NULL,
    [DateCreated]           DATETIME      NULL,
    [DateUpdated]          DATETIME      NULL,
    [UpdateEmployeeId]             INT           NULL,
    [AreaId]            INT           NULL,
    [ProposedSolution]  VARCHAR (MAX) NULL,
    [ParentTaskId]            INT           NULL,
    CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Tasks_Areas] FOREIGN KEY ([AreaId]) REFERENCES [dbo].[Areas] ([Id]),
    CONSTRAINT [FK_Tasks_ParentTasks] FOREIGN KEY ([ParentTaskId]) REFERENCES [dbo].[Tasks] ([Id]),
    CONSTRAINT [FK_Tasks_Portfolios] FOREIGN KEY ([PortfolioId]) REFERENCES [dbo].[Portfolios] ([Id]),
    CONSTRAINT [FK_Tasks_PortfolioMeasurementUnits] FOREIGN KEY ([PortfolioMeasurementUnitId]) REFERENCES [dbo].[MeasurementUnits] ([Id]),
    CONSTRAINT [FK_Tasks_SolverEmployees] FOREIGN KEY ([SolverEmployeeId]) REFERENCES [dbo].[Employees] ([Id]),
    CONSTRAINT [FK_Tasks_TaskStates] FOREIGN KEY ([TaskStateId]) REFERENCES [dbo].[TaskStates] ([Id]),
    CONSTRAINT [FK_Tasks_TaskTypes] FOREIGN KEY ([TaskTypeId]) REFERENCES [dbo].[TaskTypes] ([Id]),
    CONSTRAINT [FK_Tasks_UpdateEmployees] FOREIGN KEY ([UpdateEmployeeId]) REFERENCES [dbo].[Employees] ([Id]),
    CONSTRAINT [FK_Tasks_StartupWorks] FOREIGN KEY (StartupWorkId) REFERENCES [dbo].[StartupWorks] ([Id]),
    CONSTRAINT [FK_Tasks_Contracts] FOREIGN KEY ([ContractId]) REFERENCES [dbo].[Contracts] ([Id])
);

